---
title: "similar_codes_count_examples"
author: "Ric Campbell"
date: "19/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(ggplot2)
library(scales)
library(kableExtra)
library(lubridate)

### Create merged dataset of IE admissions and the invasive medical procedures that happen in the 15 months prior to them

## Read in IE cohort

  ie_cohort <- readRDS("D:/I-SPIEDM/I-SPIEDM/data/datasets/IE_cohort_risk_discharge_causal_180_UoS_2021-06-15.rds")
  
  invasive_procedures <- readRDS("D:/I-SPIEDM/I-SPIEDM/data/datasets/first_invasive_procedure_per_code_per_date_patient.rds")
  
  
## Reduce to only IE cases of interest, and create admission month field
  
  ie_cohort <- ie_cohort[index_admission == TRUE]
  ie_cohort[, admission_month := floor_date(ADMIDATE, unit = "month")]
  

## Give all IE and invasive procedures an ID (first half of id name will be added below)
  
  ie_cohort[, id := 1:.N]
  invasive_procedures[, id := 1:.N]

## Change names so can tell fields apart
  
  setnames(ie_cohort, setdiff(colnames(ie_cohort), "ENCRYPTED_HESID"),
           paste("ie", setdiff(colnames(ie_cohort), "ENCRYPTED_HESID"), sep = "_"))
  
  setnames(invasive_procedures, setdiff(colnames(invasive_procedures), "ENCRYPTED_HESID"),
           paste("invasive", setdiff(colnames(invasive_procedures), "ENCRYPTED_HESID"), sep = "_"))
  
  
## Merge together IE cases with all invasive procedures (are we interested in IE admissions with no invasive procedures)
  
  ie_invasive <- merge(ie_cohort,
                       invasive_procedures,
                       by = "ENCRYPTED_HESID",
                       all = FALSE)
  
  
## Create field with time between IE admission and invasive procedure  
  
  ie_invasive[, days_to_admission := as.integer(invasive_ADMIDATE - ie_ADMIDATE)]
  
  
## Retain only records that had invasive procedure prior to IE admission (do we want ones that are same day?)
  
  invasive_before_ie <- ie_invasive[days_to_admission <= 0]
  
  
## Create month splits for time of invasive procedure in relation to IE admission, one for with and one for without day of admissions
  
  invasive_before_ie[, months_to_admission_with_admi_day := ceiling(days_to_admission / 30) - 1L]
  invasive_before_ie[days_to_admission != 0
                     , months_to_admission_without_admi_day := ceiling((days_to_admission + 1L) / 30) - 1L]
  

## No need to reduce IE admissions as have 10 years of HES data prior to first IE admission in 2010
  
## Remove any records that are more than 15 months prior to IE admission
## Have to create two table as they are different limits and cannot limit in table creation below as need them as characters

  invasive_before_ie_with <- invasive_before_ie[months_to_admission_with_admi_day >= -15L]
  
  invasive_before_ie_without <- invasive_before_ie[months_to_admission_without_admi_day >= -15L]
  
  
## Only want to look at broad definition
  
  invasive_before_ie_without <- invasive_before_ie_without[ie_condition == "Infective Endocarditis broad"]

```


```{r find_examples, include=FALSE}



## Look for people with lots of procedures at onces

  invasive_before_ie_without[, .N, by = .(ENCRYPTED_HESID, invasive_ADMIDATE)][order(-N)]
  
  
  invasive_before_ie_without[ENCRYPTED_HESID == "A7EBFF16FE189E31B3443FCD6DF4FEC5" & invasive_ADMIDATE == "2010-10-20",
                             .(ENCRYPTED_HESID, invasive_ADMIDATE, invasive_diag_code, invasive_full_title, invasive_procedure, invasive_procedure_group,
                               days_to_admission)][order(days_to_admission, invasive_procedure_group, invasive_procedure, invasive_diag_code)]


    
## One that are good examples for a table
  
  example_table <- invasive_before_ie_without[(ENCRYPTED_HESID == "D4360405081782328CFB0414CE1128A4" & invasive_ADMIDATE == "2012-08-07" &
                                                 invasive_procedure_group == "cardiac")
                                              | (ENCRYPTED_HESID == "A548F3E0895EA0B0437D068FC594A6B3" & invasive_ADMIDATE == "2011-08-10" &
                                                   invasive_procedure_group == "skin")
                                              |(ENCRYPTED_HESID == "BD6F7B1E3E8511FC49C19AA47280F483" & invasive_ADMIDATE == "2010-08-31" &
                                                  invasive_procedure_group == "cardiac"),
                                              .(ENCRYPTED_HESID, invasive_ADMIDATE, invasive_diag_code, invasive_full_title,
                                                invasive_procedure, invasive_procedure_group)][order(invasive_procedure_group, invasive_procedure,
                                                                                                     invasive_diag_code)][, patient_id := .GRP, by = ENCRYPTED_HESID]
  
  example_table[, c("ENCRYPTED_HESID", "invasive_ADMIDATE") := NULL]
  
  setcolorder(example_table, c("patient_id"))
  
  setorder(example_table, patient_id, invasive_procedure_group, invasive_procedure, invasive_diag_code)


```


```{r output, include = TRUE}

column_spec(kable_styling(kable(example_table, align = "r"), bootstrap_options = c("hover", "condensed"), fixed_thead = TRUE), 1, bold = TRUE)

```





