---
title: "IE cases and procedures over time"
author: "Ric Campbell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

## FOR INTERNAL PROJECT USE ONLY

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(ggplot2)
library(scales)
library(lubridate)
library(kableExtra)

      
```


```{r read_clean_data, include = FALSE}

## Read in IE cohort

  ie_cohort <- readRDS("D:/I-SPIEDM/I-SPIEDM/data/datasets/IE_cohort_risk_discharge_causal_180_UoS_2022-02-14.rds")
  
  
## Change ADMIDATE to date type
  
  ie_cohort[, ADMIDATE := as.Date(ADMIDATE, format = "%Y-%m-%d")]
  

## Reduce to only IE cases of interest, broad condition, and create admission month field

  ie_cohort <- ie_cohort[index_admission == TRUE]
  ie_cohort <- ie_cohort[condition == "Infective Endocarditis broad"]
  ie_cohort[, admission_month := floor_date(ADMIDATE, unit = "month")]

  
## Further reduction of cohort for stats checking - Feb-2022
  
  stats_cohort <- ie_cohort[index_admission_number == 1L]
  
  stats_cohort <- stats_cohort[non_elective_admission == TRUE]
  
  stats_cohort <- stats_cohort[(length_of_stay > 2L | length_of_stay < 0L |  is.na(length_of_stay)) 
                               | (discharged_alive == FALSE | is.na(discharged_alive))]
  
  
####~~~~ Read in different file dependent on selection of procedures want to look at ~~~~~~####    
  
  invasive_procedures <- readRDS("D:/I-SPIEDM/I-SPIEDM/data/datasets/first_invasive_procedure_per_procedure_per_date_patient_heart_rule.rds")
  
  invasive_procedures[, admission_month := floor_date(ADMIDATE, unit = "month")]
  
  invasive_procedures_reduced_date <- invasive_procedures[ADMIDATE >= "2009-01-01"]
  
  
## Merge together IE cases and invasive procedures so can limit to only those procedures in the 15 month prior to IE
  
  ## Change names so can tell fields apart

  setnames(stats_cohort, setdiff(colnames(stats_cohort), "ENCRYPTED_HESID"),
           paste("ie", setdiff(colnames(stats_cohort), "ENCRYPTED_HESID"), sep = "_"))
  
  setnames(invasive_procedures, setdiff(colnames(invasive_procedures), "ENCRYPTED_HESID"),
           paste("invasive", setdiff(colnames(invasive_procedures), "ENCRYPTED_HESID"), sep = "_"))
  
  
  ie_invasive <- merge(stats_cohort,
                       invasive_procedures,
                       by = "ENCRYPTED_HESID",
                       all.x = TRUE)


## Create field with time between IE admission and invasive procedure  

  ie_invasive[, days_to_admission := as.integer(invasive_ADMIDATE - ie_ADMIDATE)]


## Retain only records that had invasive procedure prior to IE admission (do we want ones that are same day?)

  invasive_before_ie <- ie_invasive[days_to_admission <= 0]


## Retain only records that have an invasive procedure that follows the heart rule (certain procedures can't be on same admissions as heart valve repair/replace)

  invasive_before_ie_heart_rule <- invasive_before_ie[invasive_valid_procedure_including_heart_rule == TRUE
                                                      | is.na(invasive_valid_procedure_including_heart_rule)]

  
## Create month splits for time of invasive procedure in relation to IE admission, one for with and one for without day of admissions

  invasive_before_ie_heart_rule[, months_to_admission_with_admi_day := ceiling(days_to_admission / 30) - 1L]
  invasive_before_ie_heart_rule[days_to_admission != 0
                                , months_to_admission_without_admi_day := ceiling((days_to_admission + 1L) / 30) - 1L]


## No need to reduce IE admissions as have 10 years of HES data prior to first IE admission in 2010

## Remove any records that are more than 15 months prior to IE admission
## Have to create two table as they are different limits and cannot limit in table creation below as need them as characters
  
  invasive_before_ie_heart_rule_with <- invasive_before_ie_heart_rule[months_to_admission_with_admi_day >= -15L]
  
  invasive_before_ie_heart_rule_without <- invasive_before_ie_heart_rule[months_to_admission_without_admi_day >= -15L]
  
  
## Further reduction of cohort for stats checking - Feb-2022
## Keep only the first observation for each patient-procedure-month
  
  setorder(invasive_before_ie_heart_rule_without, ENCRYPTED_HESID, ie_ADMIDATE, invasive_procedure, months_to_admission_without_admi_day)
  
  invasive_before_ie_heart_rule_without[, procedure_count := 1:.N, by = .(ENCRYPTED_HESID, invasive_procedure, months_to_admission_without_admi_day)]
  
  single_procedure_month_patient <- invasive_before_ie_heart_rule_without[procedure_count == 1L]

```


## Graphs looking at individual procedure types prior to IE
These graphs include only those invasive procedures that happened in the 15 months prior to an IE admission, and does not include those that occur on the same day as the IE admission. They also only include one procedure-patient-month prior to IE admission triplet

```{r, echo = FALSE, message = FALSE}

  ggplot(single_procedure_month_patient[invasive_procedure == "blood_transfusion",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of blood transfusion procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
  
  
  ggplot(single_procedure_month_patient[invasive_procedure == "bone_marrow_puncture",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of bone marrow puncture procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
  
  
  ggplot(single_procedure_month_patient[invasive_procedure == "cystoscopic",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of cystoscopic procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
  
  
  ggplot(single_procedure_month_patient[invasive_procedure == "endoscopic_prostate",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of endoscopic prostate procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
  
  
  ggplot(single_procedure_month_patient[invasive_procedure == "haemodialysis_haemofiltration_haemoperfusion",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of haemodialysis haemofiltration haemoperfusion procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
  
  
  ggplot(single_procedure_month_patient[invasive_procedure == "coronary_angiography",
                                        .N, by = months_to_admission_without_admi_day],
         mapping = aes(x = months_to_admission_without_admi_day, y = N)) +
    geom_bar(stat = "identity", color = "Red", fill = "indianred2") +
    labs(title = paste(strwrap("Number of coronary angiography procedures per broad IE case that are included in the 15 months invasive procedures are being counted for, including admission month", 80), collapse = "\n"))
```







